### ISSUE TITLE
[REQUEST] Please add a solution for razor based views

### ISSUE THREAD

**Issue by HamedFathi** [elanderson/ASP.NET-Core-Basics#10]
Hello @elanderson

Thanks for your awesome tutorial.

Can you add a razor solution too ? 
You defined ClientApp and It includes .html so How to use cshtmls (razor) against simple html in the other words I want to have pair .ts .cshtml 

Can this possible ?

Thanks

**Comment by elanderson** [comment]
@HamedFathi your welcome! There are a set of razor views in the Contacts project.

I don't think that is what you are looking for. What are you trying to do by pairing .ts and .cshtml files? The idea of both Angular and Aurelia is that the pairing is really for the client side. The .cshtml files have to be processed on the server.
