### ISSUE TITLE
[ERROR] Cannot find module './wwwroot/dist/vendor-manifest.json' in Aurelia project

### ISSUE THREAD

**Issue by HamedFathi** [elanderson/ASP.NET-Core-Basics#11]
Hello

Can you say, why do I run the 'webpack' command or running 'Aurelia project' with VS have an error ?

```
C:\Users\...\Desktop\ASP.NET Core Basics\src\Aurelia>webpack
module.js:471
    throw err;
    ^

Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\...\Desktop\ASP.NET Core Basics\src\Aurelia\webpack.config.js:27:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (C:\Users\...\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:96:18)
    at C:\Users\...\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (C:\Users\...\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:107:15)

C:\Users\...\Desktop\ASP.NET Core Basics\src\Aurelia>
```

![1](https://cloud.githubusercontent.com/assets/8418700/24332097/d92a3bfc-1255-11e7-9773-f24b7d44961f.png)
![2](https://cloud.githubusercontent.com/assets/8418700/24332110/076ec9ec-1256-11e7-960c-8515dd2e4cfa.png)

Can you help me for run 'Aurelia project' ?

**Comment by elanderson** [comment]
Try the information in [this](https://elanderson.net/2016/12/aurelia-with-javascriptservices-call-to-node-module-failed/) post.

The gist is basically to run this command: webpack --config webpack.config.vendor.js

**Comment by HamedFathi** [comment]
@elanderson 

Thanks for your answer, but I think you should change something in your 'webpack.config.js','webpack.config.vendor.js'.

after run the above command I have an error 

```
Error: Module 'C:\Users\...\Desktop\ASP.NET Core Basics\src\Aurelia\
modules\css\index.js' is not a loader (must have normal or pitch function)
```

so I searched and found this

**Automatic -loader module name extension removed**
[https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed](https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed)


then I added **'-loader'** to all loader configuration. Now Works :)

thanks

**Comment by elanderson** [comment]
Sounds like it is time to update his project. This example is from when JavaScriptServices was using Webpack 1.

**Comment by HamedFathi** [comment]
@elanderson 

Can you update to webpack 2 ? after updating the project.json I have error 
[https://github.com/aurelia/webpack-plugin/issues/97](https://github.com/aurelia/webpack-plugin/issues/97)

Anyway, Thanks

**Comment by elanderson** [comment]
@HamedFathi I will check into it, but it may be a couple of weeks before I can get to it.

**Comment by elanderson** [comment]
@HamedFathi  projects have been updated. Before the first run the following command must be run in both the Angular and Aurelia project directories.

webpack.js --config webpack.config.vendor.js

**Comment by HamedFathi** [comment]
@elanderson Thanks
